---
title: ""
---

::: pub-hero
# Publications

Selected publications from Yong-Yeon Cho’s Lab\
(Only articles by the corresponding author and co-corresponding authors are displayed; for further details, please refer to the [university's official website](https://pharmacy.catholic.ac.kr/pharmacy/faculty/faculty.do?mode=view&persNo=211110076){target="_blank"} or [Google Scholar](https://scholar.google.com/citations?hl=ko&user=Q4GdE4MAAAAJ&view_op=list_works&sortby=pubdate){target="_blank"}.)
:::

:::::::::::: pub-year
## 2025

::::::::::: pub-list
:::::: pub-item
#### New Roles of bZIP-Containing Membrane-Bound Transcription Factors in Chromatin Tethering and Karyoptosis

::: pub-authors
Jeung, D., Li, X., & Cho, Y.-Y.
:::

::: pub-journal
*International Journal of Molecular Sciences*, 26(22)
:::

::: pub-links
[DOI](https://doi.org/10.3390/ijms262210896){target="_blank"}
:::
::::::

:::::: pub-item
#### RSK2 and its binding partners: An emerging signaling node in cancers

::: pub-authors
Lee, H. S., Cho, S.-J., Kang, H. C., Lee, J. Y., Kwon, Y. J., & Cho, Y.-Y.
:::

::: pub-journal
*Archives of Pharmacal Research*, 48(5), 365–383
:::

::: pub-links
[DOI](https://doi.org/10.1007/s12272-025-01543-3){target="_blank"}
:::
::::::
:::::::::::
::::::::::::

:::::::::::::::::::: pub-year
## 2024

::::::::::::::::::: pub-list
:::::: pub-item
#### Karyoptosis as a novel type of UVB-induced regulated cell death

::: pub-authors
Chen, W., Byun, J., Kang, H. C., Lee, H. S., Lee, J. Y., Kwon, Y. J., & Cho, Y.-Y.
:::

::: pub-journal
*Free Radical Research*, 58(11), 796–810
:::

::: pub-links
[DOI](https://doi.org/10.1080/10715762.2024.2433986){target="_blank"}
:::
::::::

:::::: pub-item
#### RSK2-mediated cGAS phosphorylation induces cGAS chromatin-incorporation-mediated cell transformation and cancer cell colony growth

::: pub-authors
Chen, W., Byun, J., Kang, H. C., Lee, H. S., Lee, J. Y., Kwon, Y. J., & Cho, Y.-Y.
:::

::: pub-journal
*Cell Death Discovery*, 10(1), 442
:::

::: pub-links
[DOI](https://doi.org/10.1038/s41420-024-02208-8){target="_blank"}
:::
::::::

:::::: pub-item
#### SPOP-mediated RIPK3 destabilization desensitizes LPS/sMAC/zVAD-induced necroptotic cell death

::: pub-authors
Lee, G.-E., Bang, G., Byun, J., Chen, W., Jeung, D., Cho, H., Lee, J. Y., Kang, H. C., Lee, H. S., Kim, K. D., Nam, S.-B., Lee, C.-J., Kwon, Y. J., Lee, C.-J., & Cho, Y.-Y.
:::

::: pub-journal
*Cellular and Molecular Life Sciences*, 81(1), 451
:::

::: pub-links
[DOI](https://doi.org/10.1007/s00018-024-05487-7){target="_blank"}
:::
::::::

:::::: pub-item
#### Dysregulated CREB3 cleavage at the nuclear membrane induces karyoptosis-mediated cell death

::: pub-authors
Lee, G.-E., Bang, G., Byun, J., Lee, C.-J., Chen, W., Jeung, D., Cho, H., Lee, J. Y., Kang, H. C., Lee, H. S., Kim, J. Y., Kim, K. D., Wu, J., Nam, S.-B., Kwon, Y. J., Lee, C.-J., & Cho, Y.-Y.
:::

::: pub-journal
*Experimental & Molecular Medicine*, 56(3), 686–699
:::

::: pub-links
[DOI](https://doi.org/10.1038/s12276-024-01195-1){target="_blank"}
:::
::::::
:::::::::::::::::::
::::::::::::::::::::

:::::::::::::::::::: pub-year
## 2023

::::::::::::::::::: pub-list
:::::: pub-item
#### Cyclic GMP-AMP Synthase in Cancer Prevention

::: pub-authors
Chen, W., Lee, G.-E., Jeung, D., Byun, J., Juan, W., & Cho, Y.-Y.
:::

::: pub-journal
*Journal of Cancer Prevention*, 28(4), 143–196
:::

::: pub-links
[DOI](https://doi.org/10.15430/JCP.2023.28.4.143){target="_blank"}
:::
::::::

:::::: pub-item
#### Novel wiring of the AKT-RSK2 signaling pathway plays an essential role in cancer cell proliferation via a G1/S cell cycle transition

::: pub-authors
Choi, J.-S., & Cho, Y.-Y.
:::

::: pub-journal
*Biochemical and Biophysical Research Communications*, 642, 66–74
:::

::: pub-links
[DOI](https://doi.org/10.1016/j.bbrc.2022.12.048){target="_blank"}
:::
::::::

:::::: pub-item
#### Molecular Mechanisms for the Regulation of Nuclear Membrane Integrity

::: pub-authors
Lee, G.-E., Byun, J., Lee, C.-J., & Cho, Y.-Y.
:::

::: pub-journal
*International Journal of Molecular Sciences*, 24(20)
:::

::: pub-links
[DOI](https://doi.org/10.3390/ijms242015497){target="_blank"}
:::
::::::

:::::: pub-item
#### MEKs/ERKs-mediated FBXO1/E2Fs interaction interference modulates G1/S cell cycle transition and cancer cell proliferation

::: pub-authors
Lee, G.-E., Jeung, D., Chen, W., Byun, J., Lee, J. Y., Kang, H. C., Lee, H. S., Kim, D. J., Choi, J.-S., Lee, C.-J., An, H.-J., & Cho, Y.-Y.
:::

::: pub-journal
*Archives of Pharmacal Research*, 46(1), 44–58
:::

::: pub-links
[DOI](https://doi.org/10.1007/s12272-023-01426-5){target="_blank"}
:::
::::::
:::::::::::::::::::
::::::::::::::::::::

:::::::::::::::: pub-year
## 2022

::::::::::::::: pub-list
:::::: pub-item
#### FBXW7-mediated ERK3 degradation regulates the proliferation of lung cancer cells

::: pub-authors
An, H.-J., Lee, C.-J., Lee, G.-E., Choi, Y., Jeung, D., Chen, W., Lee, H. S., Kang, H. C., Lee, J. Y., Kim, D. J., Choi, J.-S., Cho, E. S., Choi, J.-S., & Cho, Y.-Y.
:::

::: pub-journal
*Experimental & Molecular Medicine*, 54(1), 35–46
:::

::: pub-links
[DOI](https://doi.org/10.1038/s12276-021-00721-9){target="_blank"}
:::
::::::

:::::: pub-item
#### Abstract 5695: Roles of cGAS in DNA damage response

::: pub-authors
Chen, W., An, H.-J., Lee, G.-E., & Cho, Y.-Y.
:::

::: pub-journal
*Cancer Research*, 82(12 Supplement), 5695
:::

::: pub-links
[DOI](https://doi.org/10.1158/1538-7445.AM2022-5695){target="_blank"}
:::
::::::

:::::: pub-item
#### Abstract 5677: βTrCP1 is a substrate of extracellular signal-regulated kinase 2

::: pub-authors
Lee, G.-E., Lee, C.-J., An, H.-J., Chen, W., Jeung, D., Choi, Y., & Cho, Y.-Y.
:::

::: pub-journal
*Cancer Research*, 82(12 Supplement), 5677
:::

::: pub-links
[DOI](https://doi.org/10.1158/1538-7445.AM2022-5677){target="_blank"}
:::
::::::
:::::::::::::::
::::::::::::::::

:::::::::::::::: pub-year
## 2021

::::::::::::::: pub-list
:::::: pub-item
#### F-box Protein βTrCP1 Is a Substrate of Extracellular Signal-regulated Kinase 2

::: pub-authors
Lee, C.-J., Lee, G.-E., An, H.-J., Cho, E. S., Chen, W., Lee, J. Y., Kang, H. C., Lee, H. S., & Cho, Y.-Y.
:::

::: pub-journal
*Journal of Cancer Prevention*, 26(3), 174–182
:::

::: pub-links
[DOI](https://doi.org/10.15430/JCP.2021.26.3.174){target="_blank"}
:::
::::::

:::::: pub-item
#### Fargesin Inhibits EGF-Induced Cell Transformation and Colon Cancer Cell Growth by Suppression of CDK2/Cyclin E Signaling Pathway

::: pub-authors
Lee, G.-E., Lee, C.-J., An, H.-J., Kang, H. C., Lee, H. S., Lee, J. Y., Oh, S.-R., Cho, S.-J., Kim, D. J., & Cho, Y.-Y.
:::

::: pub-journal
*International Journal of Molecular Sciences*, 22(4)
:::

::: pub-links
[DOI](https://doi.org/10.3390/ijms22042073){target="_blank"}
:::
::::::

:::::: pub-item
#### Kaempferol sensitizes cell proliferation inhibition in oxaliplatin-resistant colon cancer cells

::: pub-authors
Park, J., Lee, G.-E., An, H.-J., Lee, C.-J., Cho, E. S., Kang, H. C., Lee, J. Y., Lee, H. S., Choi, J.-S., Kim, D. J., Choi, J.-S., & Cho, Y.-Y.
:::

::: pub-journal
*Archives of Pharmacal Research*, 44(12), 1091–1108
:::

::: pub-links
[DOI](https://doi.org/10.1007/s12272-021-01358-y){target="_blank"}
:::
::::::
:::::::::::::::
::::::::::::::::

:::::::::::: pub-year
## 2020

::::::::::: pub-list
:::::: pub-item
#### Stat2 stability regulation: An intersection between immunity and carcinogenesis

::: pub-authors
Lee, C.-J., An, H.-J., Cho, E. S., Kang, H. C., Lee, J. Y., Lee, H. S., & Cho, Y.-Y.
:::

::: pub-journal
*Experimental & Molecular Medicine*, 52(9), 1526–1536
:::

::: pub-links
[DOI](https://doi.org/10.1038/s12276-020-00506-6){target="_blank"}
:::
::::::

:::::: pub-item
#### FBXW7-mediated stability regulation of signal transducer and activator of transcription 2 in melanoma formation

::: pub-authors
Lee, C.-J., An, H.-J., Kim, S.-M., Yoo, S.-M., Park, J., Lee, G.-E., Kim, W.-Y., Kim, D. J., Kang, H. C., Lee, J. Y., Lee, H. S., Cho, S.-J., & Cho, Y.-Y.
:::

::: pub-journal
*Proceedings of the National Academy of Sciences*, 117(1), 584–594
:::

::: pub-links
[DOI](https://doi.org/10.1073/pnas.1909879116){target="_blank"}
:::
::::::
:::::::::::
::::::::::::

::: pub-note
More publications and updates will be added as the website continues to develop.
:::
